package biz.advancedcalendar.wsdl.sync;

// ----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 07-11-2014
//
// ---------------------------------------------------
import java.util.ArrayList;
import java.util.List;

public class Label {
	public Long CompanyID;
	public List<Long> Contacts = new ArrayList<Long>();
	public java.util.Date Created;
	public Boolean Deleted;
	public String Description;
	public List<Long> Files = new ArrayList<Long>();
	public Boolean IsCompany;
	public Boolean IsSection;
	public Long Id;
	public String Text;
	public java.util.Date LastMod;
	public Long OriginalID;
	public Long ParentId;
	public Integer SortOrder;
	public List<Long> Tasks = new ArrayList<Long>();
	public String UserName;

	public Label() {
	}
}
