package biz.advancedcalendar.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import biz.advancedcalendar.greendao.ContactData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CONTACT_DATA.
*/
public class ContactDataDao extends AbstractDao<ContactData, Long> {

    public static final String TABLENAME = "CONTACT_DATA";

    /**
     * Properties of entity ContactData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ServerId = new Property(1, Long.class, "ServerId", false, "SERVER_ID");
        public final static Property LocalContactId = new Property(2, Long.class, "LocalContactId", false, "LOCAL_CONTACT_ID");
        public final static Property Type = new Property(3, Short.class, "Type", false, "TYPE");
        public final static Property Value = new Property(4, String.class, "Value", false, "VALUE");
        public final static Property Name = new Property(5, String.class, "Name", false, "NAME");
        public final static Property SortOrder = new Property(6, Integer.class, "SortOrder", false, "SORT_ORDER");
    };

    private DaoSession daoSession;

    private Query<ContactData> contact_ContactDataListQuery;

    public ContactDataDao(DaoConfig config) {
        super(config);
    }
    
    public ContactDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CONTACT_DATA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SERVER_ID' INTEGER," + // 1: ServerId
                "'LOCAL_CONTACT_ID' INTEGER," + // 2: LocalContactId
                "'TYPE' INTEGER," + // 3: Type
                "'VALUE' TEXT," + // 4: Value
                "'NAME' TEXT," + // 5: Name
                "'SORT_ORDER' INTEGER);"); // 6: SortOrder
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CONTACT_DATA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ContactData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long ServerId = entity.getServerId();
        if (ServerId != null) {
            stmt.bindLong(2, ServerId);
        }
 
        Long LocalContactId = entity.getLocalContactId();
        if (LocalContactId != null) {
            stmt.bindLong(3, LocalContactId);
        }
 
        Short Type = entity.getType();
        if (Type != null) {
            stmt.bindLong(4, Type);
        }
 
        String Value = entity.getValue();
        if (Value != null) {
            stmt.bindString(5, Value);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(6, Name);
        }
 
        Integer SortOrder = entity.getSortOrder();
        if (SortOrder != null) {
            stmt.bindLong(7, SortOrder);
        }
    }

    @Override
    protected void attachEntity(ContactData entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ContactData readEntity(Cursor cursor, int offset) {
        ContactData entity = new ContactData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // ServerId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // LocalContactId
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3), // Type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Value
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Name
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6) // SortOrder
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ContactData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setServerId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLocalContactId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3));
        entity.setValue(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSortOrder(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ContactData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ContactData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "contactDataList" to-many relationship of Contact. */
    public List<ContactData> _queryContact_ContactDataList(Long LocalContactId) {
        synchronized (this) {
            if (contact_ContactDataListQuery == null) {
                QueryBuilder<ContactData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LocalContactId.eq(null));
                contact_ContactDataListQuery = queryBuilder.build();
            }
        }
        Query<ContactData> query = contact_ContactDataListQuery.forCurrentThread();
        query.setParameter(0, LocalContactId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getContactDao().getAllColumns());
            builder.append(" FROM CONTACT_DATA T");
            builder.append(" LEFT JOIN CONTACT T0 ON T.'LOCAL_CONTACT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ContactData loadCurrentDeep(Cursor cursor, boolean lock) {
        ContactData entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Contact contact = loadCurrentOther(daoSession.getContactDao(), cursor, offset);
        entity.setContact(contact);

        return entity;    
    }

    public ContactData loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ContactData> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ContactData> list = new ArrayList<ContactData>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ContactData> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ContactData> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
