package biz.advancedcalendar.greendao;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession */
public class DaoSession extends AbstractDaoSession {
	private final DaoConfig userProfileDaoConfig;
	private final DaoConfig calendarDaoConfig;
	private final DaoConfig taskDaoConfig;
	private final DaoConfig taskOccurrenceDaoConfig;
	private final DaoConfig reminderDaoConfig;
	private final DaoConfig scheduledReminderDaoConfig;
	private final DaoConfig elapsedReminderDaoConfig;
	private final DaoConfig labelDaoConfig;
	private final DaoConfig contactDaoConfig;
	private final DaoConfig contactDataDaoConfig;
	private final DaoConfig fileDaoConfig;
	private final DaoConfig workGroupDaoConfig;
	private final DaoConfig workGroupMemberDaoConfig;
	private final DaoConfig messageDaoConfig;
	private final DaoConfig diaryRecordDaoConfig;
	private final DaoConfig taskLabelDaoConfig;
	private final DaoConfig diaryRecordLabelDaoConfig;
	private final DaoConfig labelContactDaoConfig;
	private final DaoConfig taskContactDaoConfig;
	private final DaoConfig fileTaskDaoConfig;
	private final DaoConfig fileLabelDaoConfig;
	private final DaoConfig fileContactDaoConfig;
	private final UserProfileDao userProfileDao;
	private final CalendarDao calendarDao;
	private final TaskDao taskDao;
	private final TaskOccurrenceDao taskOccurrenceDao;
	private final ReminderDao reminderDao;
	private final ScheduledReminderDao scheduledReminderDao;
	private final ElapsedReminderDao elapsedReminderDao;
	private final LabelDao labelDao;
	private final ContactDao contactDao;
	private final ContactDataDao contactDataDao;
	private final FileDao fileDao;
	private final WorkGroupDao workGroupDao;
	private final WorkGroupMemberDao workGroupMemberDao;
	private final MessageDao messageDao;
	private final DiaryRecordDao diaryRecordDao;
	private final TaskLabelDao taskLabelDao;
	private final DiaryRecordLabelDao diaryRecordLabelDao;
	private final LabelContactDao labelContactDao;
	private final TaskContactDao taskContactDao;
	private final FileTaskDao fileTaskDao;
	private final FileLabelDao fileLabelDao;
	private final FileContactDao fileContactDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);
		userProfileDaoConfig = daoConfigMap.get(UserProfileDao.class).clone();
		userProfileDaoConfig.initIdentityScope(type);
		calendarDaoConfig = daoConfigMap.get(CalendarDao.class).clone();
		calendarDaoConfig.initIdentityScope(type);
		taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
		taskDaoConfig.initIdentityScope(type);
		taskOccurrenceDaoConfig = daoConfigMap.get(TaskOccurrenceDao.class).clone();
		taskOccurrenceDaoConfig.initIdentityScope(type);
		reminderDaoConfig = daoConfigMap.get(ReminderDao.class).clone();
		reminderDaoConfig.initIdentityScope(type);
		scheduledReminderDaoConfig = daoConfigMap.get(ScheduledReminderDao.class).clone();
		scheduledReminderDaoConfig.initIdentityScope(type);
		elapsedReminderDaoConfig = daoConfigMap.get(ElapsedReminderDao.class).clone();
		elapsedReminderDaoConfig.initIdentityScope(type);
		labelDaoConfig = daoConfigMap.get(LabelDao.class).clone();
		labelDaoConfig.initIdentityScope(type);
		contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
		contactDaoConfig.initIdentityScope(type);
		contactDataDaoConfig = daoConfigMap.get(ContactDataDao.class).clone();
		contactDataDaoConfig.initIdentityScope(type);
		fileDaoConfig = daoConfigMap.get(FileDao.class).clone();
		fileDaoConfig.initIdentityScope(type);
		workGroupDaoConfig = daoConfigMap.get(WorkGroupDao.class).clone();
		workGroupDaoConfig.initIdentityScope(type);
		workGroupMemberDaoConfig = daoConfigMap.get(WorkGroupMemberDao.class).clone();
		workGroupMemberDaoConfig.initIdentityScope(type);
		messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
		messageDaoConfig.initIdentityScope(type);
		diaryRecordDaoConfig = daoConfigMap.get(DiaryRecordDao.class).clone();
		diaryRecordDaoConfig.initIdentityScope(type);
		taskLabelDaoConfig = daoConfigMap.get(TaskLabelDao.class).clone();
		taskLabelDaoConfig.initIdentityScope(type);
		diaryRecordLabelDaoConfig = daoConfigMap.get(DiaryRecordLabelDao.class).clone();
		diaryRecordLabelDaoConfig.initIdentityScope(type);
		labelContactDaoConfig = daoConfigMap.get(LabelContactDao.class).clone();
		labelContactDaoConfig.initIdentityScope(type);
		taskContactDaoConfig = daoConfigMap.get(TaskContactDao.class).clone();
		taskContactDaoConfig.initIdentityScope(type);
		fileTaskDaoConfig = daoConfigMap.get(FileTaskDao.class).clone();
		fileTaskDaoConfig.initIdentityScope(type);
		fileLabelDaoConfig = daoConfigMap.get(FileLabelDao.class).clone();
		fileLabelDaoConfig.initIdentityScope(type);
		fileContactDaoConfig = daoConfigMap.get(FileContactDao.class).clone();
		fileContactDaoConfig.initIdentityScope(type);
		userProfileDao = new UserProfileDao(userProfileDaoConfig, this);
		calendarDao = new CalendarDao(calendarDaoConfig, this);
		taskDao = new TaskDao(taskDaoConfig, this);
		taskOccurrenceDao = new TaskOccurrenceDao(taskOccurrenceDaoConfig, this);
		reminderDao = new ReminderDao(reminderDaoConfig, this);
		scheduledReminderDao = new ScheduledReminderDao(scheduledReminderDaoConfig, this);
		elapsedReminderDao = new ElapsedReminderDao(elapsedReminderDaoConfig, this);
		labelDao = new LabelDao(labelDaoConfig, this);
		contactDao = new ContactDao(contactDaoConfig, this);
		contactDataDao = new ContactDataDao(contactDataDaoConfig, this);
		fileDao = new FileDao(fileDaoConfig, this);
		workGroupDao = new WorkGroupDao(workGroupDaoConfig, this);
		workGroupMemberDao = new WorkGroupMemberDao(workGroupMemberDaoConfig, this);
		messageDao = new MessageDao(messageDaoConfig, this);
		diaryRecordDao = new DiaryRecordDao(diaryRecordDaoConfig, this);
		taskLabelDao = new TaskLabelDao(taskLabelDaoConfig, this);
		diaryRecordLabelDao = new DiaryRecordLabelDao(diaryRecordLabelDaoConfig, this);
		labelContactDao = new LabelContactDao(labelContactDaoConfig, this);
		taskContactDao = new TaskContactDao(taskContactDaoConfig, this);
		fileTaskDao = new FileTaskDao(fileTaskDaoConfig, this);
		fileLabelDao = new FileLabelDao(fileLabelDaoConfig, this);
		fileContactDao = new FileContactDao(fileContactDaoConfig, this);
		registerDao(UserProfile.class, userProfileDao);
		registerDao(Calendar.class, calendarDao);
		registerDao(Task.class, taskDao);
		registerDao(TaskOccurrence.class, taskOccurrenceDao);
		registerDao(Reminder.class, reminderDao);
		registerDao(ScheduledReminder.class, scheduledReminderDao);
		registerDao(ElapsedReminder.class, elapsedReminderDao);
		registerDao(Label.class, labelDao);
		registerDao(Contact.class, contactDao);
		registerDao(ContactData.class, contactDataDao);
		registerDao(File.class, fileDao);
		registerDao(WorkGroup.class, workGroupDao);
		registerDao(WorkGroupMember.class, workGroupMemberDao);
		registerDao(Message.class, messageDao);
		registerDao(DiaryRecord.class, diaryRecordDao);
		registerDao(TaskLabel.class, taskLabelDao);
		registerDao(DiaryRecordLabel.class, diaryRecordLabelDao);
		registerDao(LabelContact.class, labelContactDao);
		registerDao(TaskContact.class, taskContactDao);
		registerDao(FileTask.class, fileTaskDao);
		registerDao(FileLabel.class, fileLabelDao);
		registerDao(FileContact.class, fileContactDao);
	}

	public void clear() {
		userProfileDaoConfig.getIdentityScope().clear();
		calendarDaoConfig.getIdentityScope().clear();
		taskDaoConfig.getIdentityScope().clear();
		taskOccurrenceDaoConfig.getIdentityScope().clear();
		reminderDaoConfig.getIdentityScope().clear();
		scheduledReminderDaoConfig.getIdentityScope().clear();
		elapsedReminderDaoConfig.getIdentityScope().clear();
		labelDaoConfig.getIdentityScope().clear();
		contactDaoConfig.getIdentityScope().clear();
		contactDataDaoConfig.getIdentityScope().clear();
		fileDaoConfig.getIdentityScope().clear();
		workGroupDaoConfig.getIdentityScope().clear();
		workGroupMemberDaoConfig.getIdentityScope().clear();
		messageDaoConfig.getIdentityScope().clear();
		diaryRecordDaoConfig.getIdentityScope().clear();
		taskLabelDaoConfig.getIdentityScope().clear();
		diaryRecordLabelDaoConfig.getIdentityScope().clear();
		labelContactDaoConfig.getIdentityScope().clear();
		taskContactDaoConfig.getIdentityScope().clear();
		fileTaskDaoConfig.getIdentityScope().clear();
		fileLabelDaoConfig.getIdentityScope().clear();
		fileContactDaoConfig.getIdentityScope().clear();
	}

	public UserProfileDao getUserProfileDao() {
		return userProfileDao;
	}

	public CalendarDao getCalendarDao() {
		return calendarDao;
	}

	public TaskDao getTaskDao() {
		return taskDao;
	}

	public TaskOccurrenceDao getTaskOccurrenceDao() {
		return taskOccurrenceDao;
	}

	public ReminderDao getReminderDao() {
		return reminderDao;
	}

	public ScheduledReminderDao getScheduledReminderDao() {
		return scheduledReminderDao;
	}

	public ElapsedReminderDao getElapsedReminderDao() {
		return elapsedReminderDao;
	}

	public LabelDao getLabelDao() {
		return labelDao;
	}

	public ContactDao getContactDao() {
		return contactDao;
	}

	public ContactDataDao getContactDataDao() {
		return contactDataDao;
	}

	public FileDao getFileDao() {
		return fileDao;
	}

	public WorkGroupDao getWorkGroupDao() {
		return workGroupDao;
	}

	public WorkGroupMemberDao getWorkGroupMemberDao() {
		return workGroupMemberDao;
	}

	public MessageDao getMessageDao() {
		return messageDao;
	}

	public DiaryRecordDao getDiaryRecordDao() {
		return diaryRecordDao;
	}

	public TaskLabelDao getTaskLabelDao() {
		return taskLabelDao;
	}

	public DiaryRecordLabelDao getDiaryRecordLabelDao() {
		return diaryRecordLabelDao;
	}

	public LabelContactDao getLabelContactDao() {
		return labelContactDao;
	}

	public TaskContactDao getTaskContactDao() {
		return taskContactDao;
	}

	public FileTaskDao getFileTaskDao() {
		return fileTaskDao;
	}

	public FileLabelDao getFileLabelDao() {
		return fileLabelDao;
	}

	public FileContactDao getFileContactDao() {
		return fileContactDao;
	}
}
