package biz.advancedcalendar.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import biz.advancedcalendar.greendao.DiaryRecordLabel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DIARY_RECORD_LABEL.
*/
public class DiaryRecordLabelDao extends AbstractDao<DiaryRecordLabel, Long> {

    public static final String TABLENAME = "DIARY_RECORD_LABEL";

    /**
     * Properties of entity DiaryRecordLabel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DiaryRecordId = new Property(1, Long.class, "DiaryRecordId", false, "DIARY_RECORD_ID");
        public final static Property LabelId = new Property(2, Long.class, "LabelId", false, "LABEL_ID");
        public final static Property IsVirtual = new Property(3, Boolean.class, "IsVirtual", false, "IS_VIRTUAL");
    };

    private DaoSession daoSession;

    private Query<DiaryRecordLabel> diaryRecord_DiaryRecordLabelListQuery;
    private Query<DiaryRecordLabel> label_DiaryRecordLabelListQuery;

    public DiaryRecordLabelDao(DaoConfig config) {
        super(config);
    }
    
    public DiaryRecordLabelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DIARY_RECORD_LABEL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DIARY_RECORD_ID' INTEGER," + // 1: DiaryRecordId
                "'LABEL_ID' INTEGER," + // 2: LabelId
                "'IS_VIRTUAL' INTEGER);"); // 3: IsVirtual
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_DIARY_RECORD_LABEL_DIARY_RECORD_ID_LABEL_ID ON DIARY_RECORD_LABEL" +
                " (DIARY_RECORD_ID,LABEL_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DIARY_RECORD_LABEL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DiaryRecordLabel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long DiaryRecordId = entity.getDiaryRecordId();
        if (DiaryRecordId != null) {
            stmt.bindLong(2, DiaryRecordId);
        }
 
        Long LabelId = entity.getLabelId();
        if (LabelId != null) {
            stmt.bindLong(3, LabelId);
        }
 
        Boolean IsVirtual = entity.getIsVirtual();
        if (IsVirtual != null) {
            stmt.bindLong(4, IsVirtual ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(DiaryRecordLabel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DiaryRecordLabel readEntity(Cursor cursor, int offset) {
        DiaryRecordLabel entity = new DiaryRecordLabel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // DiaryRecordId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // LabelId
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // IsVirtual
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DiaryRecordLabel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDiaryRecordId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLabelId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIsVirtual(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DiaryRecordLabel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DiaryRecordLabel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "diaryRecordLabelList" to-many relationship of DiaryRecord. */
    public List<DiaryRecordLabel> _queryDiaryRecord_DiaryRecordLabelList(Long DiaryRecordId) {
        synchronized (this) {
            if (diaryRecord_DiaryRecordLabelListQuery == null) {
                QueryBuilder<DiaryRecordLabel> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DiaryRecordId.eq(null));
                diaryRecord_DiaryRecordLabelListQuery = queryBuilder.build();
            }
        }
        Query<DiaryRecordLabel> query = diaryRecord_DiaryRecordLabelListQuery.forCurrentThread();
        query.setParameter(0, DiaryRecordId);
        return query.list();
    }

    /** Internal query to resolve the "diaryRecordLabelList" to-many relationship of Label. */
    public List<DiaryRecordLabel> _queryLabel_DiaryRecordLabelList(Long LabelId) {
        synchronized (this) {
            if (label_DiaryRecordLabelListQuery == null) {
                QueryBuilder<DiaryRecordLabel> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LabelId.eq(null));
                label_DiaryRecordLabelListQuery = queryBuilder.build();
            }
        }
        Query<DiaryRecordLabel> query = label_DiaryRecordLabelListQuery.forCurrentThread();
        query.setParameter(0, LabelId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDiaryRecordDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getLabelDao().getAllColumns());
            builder.append(" FROM DIARY_RECORD_LABEL T");
            builder.append(" LEFT JOIN DIARY_RECORD T0 ON T.'DIARY_RECORD_ID'=T0.'_id'");
            builder.append(" LEFT JOIN LABEL T1 ON T.'LABEL_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DiaryRecordLabel loadCurrentDeep(Cursor cursor, boolean lock) {
        DiaryRecordLabel entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DiaryRecord diaryRecord = loadCurrentOther(daoSession.getDiaryRecordDao(), cursor, offset);
        entity.setDiaryRecord(diaryRecord);
        offset += daoSession.getDiaryRecordDao().getAllColumns().length;

        Label label = loadCurrentOther(daoSession.getLabelDao(), cursor, offset);
        entity.setLabel(label);

        return entity;    
    }

    public DiaryRecordLabel loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DiaryRecordLabel> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DiaryRecordLabel> list = new ArrayList<DiaryRecordLabel>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DiaryRecordLabel> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DiaryRecordLabel> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
