package biz.advancedcalendar.greendao;

import biz.advancedcalendar.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIARY_RECORD_LABEL.
 */
public class DiaryRecordLabel {

    private Long id;
    private Long DiaryRecordId;
    private Long LabelId;
    private Boolean IsVirtual;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DiaryRecordLabelDao myDao;

    private DiaryRecord diaryRecord;
    private Long diaryRecord__resolvedKey;

    private Label label;
    private Long label__resolvedKey;


    public DiaryRecordLabel() {
    }

    public DiaryRecordLabel(Long id) {
        this.id = id;
    }

    public DiaryRecordLabel(Long id, Long DiaryRecordId, Long LabelId, Boolean IsVirtual) {
        this.id = id;
        this.DiaryRecordId = DiaryRecordId;
        this.LabelId = LabelId;
        this.IsVirtual = IsVirtual;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDiaryRecordLabelDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDiaryRecordId() {
        return DiaryRecordId;
    }

    public void setDiaryRecordId(Long DiaryRecordId) {
        this.DiaryRecordId = DiaryRecordId;
    }

    public Long getLabelId() {
        return LabelId;
    }

    public void setLabelId(Long LabelId) {
        this.LabelId = LabelId;
    }

    public Boolean getIsVirtual() {
        return IsVirtual;
    }

    public void setIsVirtual(Boolean IsVirtual) {
        this.IsVirtual = IsVirtual;
    }

    /** To-one relationship, resolved on first access. */
    public DiaryRecord getDiaryRecord() {
        Long __key = this.DiaryRecordId;
        if (diaryRecord__resolvedKey == null || !diaryRecord__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DiaryRecordDao targetDao = daoSession.getDiaryRecordDao();
            DiaryRecord diaryRecordNew = targetDao.load(__key);
            synchronized (this) {
                diaryRecord = diaryRecordNew;
            	diaryRecord__resolvedKey = __key;
            }
        }
        return diaryRecord;
    }

    public void setDiaryRecord(DiaryRecord diaryRecord) {
        synchronized (this) {
            this.diaryRecord = diaryRecord;
            DiaryRecordId = diaryRecord == null ? null : diaryRecord.getId();
            diaryRecord__resolvedKey = DiaryRecordId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Label getLabel() {
        Long __key = this.LabelId;
        if (label__resolvedKey == null || !label__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            LabelDao targetDao = daoSession.getLabelDao();
            Label labelNew = targetDao.load(__key);
            synchronized (this) {
                label = labelNew;
            	label__resolvedKey = __key;
            }
        }
        return label;
    }

    public void setLabel(Label label) {
        synchronized (this) {
            this.label = label;
            LabelId = label == null ? null : label.getId();
            label__resolvedKey = LabelId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
