package biz.advancedcalendar.greendao;

import biz.advancedcalendar.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILE_CONTACT.
 */
public class FileContact {

    private Long id;
    private Long FileId;
    private Long ContactId;
    private Boolean IsVirtual;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient FileContactDao myDao;

    private File file;
    private Long file__resolvedKey;

    private Contact contact;
    private Long contact__resolvedKey;


    public FileContact() {
    }

    public FileContact(Long id) {
        this.id = id;
    }

    public FileContact(Long id, Long FileId, Long ContactId, Boolean IsVirtual) {
        this.id = id;
        this.FileId = FileId;
        this.ContactId = ContactId;
        this.IsVirtual = IsVirtual;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getFileContactDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFileId() {
        return FileId;
    }

    public void setFileId(Long FileId) {
        this.FileId = FileId;
    }

    public Long getContactId() {
        return ContactId;
    }

    public void setContactId(Long ContactId) {
        this.ContactId = ContactId;
    }

    public Boolean getIsVirtual() {
        return IsVirtual;
    }

    public void setIsVirtual(Boolean IsVirtual) {
        this.IsVirtual = IsVirtual;
    }

    /** To-one relationship, resolved on first access. */
    public File getFile() {
        Long __key = this.FileId;
        if (file__resolvedKey == null || !file__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            FileDao targetDao = daoSession.getFileDao();
            File fileNew = targetDao.load(__key);
            synchronized (this) {
                file = fileNew;
            	file__resolvedKey = __key;
            }
        }
        return file;
    }

    public void setFile(File file) {
        synchronized (this) {
            this.file = file;
            FileId = file == null ? null : file.getId();
            file__resolvedKey = FileId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Contact getContact() {
        Long __key = this.ContactId;
        if (contact__resolvedKey == null || !contact__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ContactDao targetDao = daoSession.getContactDao();
            Contact contactNew = targetDao.load(__key);
            synchronized (this) {
                contact = contactNew;
            	contact__resolvedKey = __key;
            }
        }
        return contact;
    }

    public void setContact(Contact contact) {
        synchronized (this) {
            this.contact = contact;
            ContactId = contact == null ? null : contact.getId();
            contact__resolvedKey = ContactId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
