package biz.advancedcalendar.greendao;

import biz.advancedcalendar.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILE_LABEL.
 */
public class FileLabel {

    private Long id;
    private Long FileId;
    private Long LabelId;
    private Boolean IsVirtual;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient FileLabelDao myDao;

    private File file;
    private Long file__resolvedKey;

    private Label label;
    private Long label__resolvedKey;


    public FileLabel() {
    }

    public FileLabel(Long id) {
        this.id = id;
    }

    public FileLabel(Long id, Long FileId, Long LabelId, Boolean IsVirtual) {
        this.id = id;
        this.FileId = FileId;
        this.LabelId = LabelId;
        this.IsVirtual = IsVirtual;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getFileLabelDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFileId() {
        return FileId;
    }

    public void setFileId(Long FileId) {
        this.FileId = FileId;
    }

    public Long getLabelId() {
        return LabelId;
    }

    public void setLabelId(Long LabelId) {
        this.LabelId = LabelId;
    }

    public Boolean getIsVirtual() {
        return IsVirtual;
    }

    public void setIsVirtual(Boolean IsVirtual) {
        this.IsVirtual = IsVirtual;
    }

    /** To-one relationship, resolved on first access. */
    public File getFile() {
        Long __key = this.FileId;
        if (file__resolvedKey == null || !file__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            FileDao targetDao = daoSession.getFileDao();
            File fileNew = targetDao.load(__key);
            synchronized (this) {
                file = fileNew;
            	file__resolvedKey = __key;
            }
        }
        return file;
    }

    public void setFile(File file) {
        synchronized (this) {
            this.file = file;
            FileId = file == null ? null : file.getId();
            file__resolvedKey = FileId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Label getLabel() {
        Long __key = this.LabelId;
        if (label__resolvedKey == null || !label__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            LabelDao targetDao = daoSession.getLabelDao();
            Label labelNew = targetDao.load(__key);
            synchronized (this) {
                label = labelNew;
            	label__resolvedKey = __key;
            }
        }
        return label;
    }

    public void setLabel(Label label) {
        synchronized (this) {
            this.label = label;
            LabelId = label == null ? null : label.getId();
            label__resolvedKey = LabelId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
