package biz.advancedcalendar.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import biz.advancedcalendar.greendao.FileLabel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FILE_LABEL.
*/
public class FileLabelDao extends AbstractDao<FileLabel, Long> {

    public static final String TABLENAME = "FILE_LABEL";

    /**
     * Properties of entity FileLabel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FileId = new Property(1, Long.class, "FileId", false, "FILE_ID");
        public final static Property LabelId = new Property(2, Long.class, "LabelId", false, "LABEL_ID");
        public final static Property IsVirtual = new Property(3, Boolean.class, "IsVirtual", false, "IS_VIRTUAL");
    };

    private DaoSession daoSession;

    private Query<FileLabel> file_FileLabelListQuery;
    private Query<FileLabel> label_FileLabelListQuery;

    public FileLabelDao(DaoConfig config) {
        super(config);
    }
    
    public FileLabelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FILE_LABEL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FILE_ID' INTEGER," + // 1: FileId
                "'LABEL_ID' INTEGER," + // 2: LabelId
                "'IS_VIRTUAL' INTEGER);"); // 3: IsVirtual
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_FILE_LABEL_FILE_ID_LABEL_ID ON FILE_LABEL" +
                " (FILE_ID,LABEL_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FILE_LABEL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FileLabel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long FileId = entity.getFileId();
        if (FileId != null) {
            stmt.bindLong(2, FileId);
        }
 
        Long LabelId = entity.getLabelId();
        if (LabelId != null) {
            stmt.bindLong(3, LabelId);
        }
 
        Boolean IsVirtual = entity.getIsVirtual();
        if (IsVirtual != null) {
            stmt.bindLong(4, IsVirtual ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(FileLabel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FileLabel readEntity(Cursor cursor, int offset) {
        FileLabel entity = new FileLabel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // FileId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // LabelId
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // IsVirtual
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FileLabel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFileId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLabelId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIsVirtual(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FileLabel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FileLabel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "fileLabelList" to-many relationship of File. */
    public List<FileLabel> _queryFile_FileLabelList(Long FileId) {
        synchronized (this) {
            if (file_FileLabelListQuery == null) {
                QueryBuilder<FileLabel> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FileId.eq(null));
                file_FileLabelListQuery = queryBuilder.build();
            }
        }
        Query<FileLabel> query = file_FileLabelListQuery.forCurrentThread();
        query.setParameter(0, FileId);
        return query.list();
    }

    /** Internal query to resolve the "fileLabelList" to-many relationship of Label. */
    public List<FileLabel> _queryLabel_FileLabelList(Long LabelId) {
        synchronized (this) {
            if (label_FileLabelListQuery == null) {
                QueryBuilder<FileLabel> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LabelId.eq(null));
                label_FileLabelListQuery = queryBuilder.build();
            }
        }
        Query<FileLabel> query = label_FileLabelListQuery.forCurrentThread();
        query.setParameter(0, LabelId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFileDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getLabelDao().getAllColumns());
            builder.append(" FROM FILE_LABEL T");
            builder.append(" LEFT JOIN FILE T0 ON T.'FILE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN LABEL T1 ON T.'LABEL_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FileLabel loadCurrentDeep(Cursor cursor, boolean lock) {
        FileLabel entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        File file = loadCurrentOther(daoSession.getFileDao(), cursor, offset);
        entity.setFile(file);
        offset += daoSession.getFileDao().getAllColumns().length;

        Label label = loadCurrentOther(daoSession.getLabelDao(), cursor, offset);
        entity.setLabel(label);

        return entity;    
    }

    public FileLabel loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FileLabel> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FileLabel> list = new ArrayList<FileLabel>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FileLabel> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FileLabel> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
