package biz.advancedcalendar.greendao;

import biz.advancedcalendar.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILE_TASK.
 */
public class FileTask implements java.io.Serializable {

    private Long id;
    private Long FileId;
    private Long TaskId;
    private Boolean IsVirtual;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient FileTaskDao myDao;

    private File file;
    private Long file__resolvedKey;

    private Task task;
    private Long task__resolvedKey;


    public FileTask() {
    }

    public FileTask(Long id) {
        this.id = id;
    }

    public FileTask(Long id, Long FileId, Long TaskId, Boolean IsVirtual) {
        this.id = id;
        this.FileId = FileId;
        this.TaskId = TaskId;
        this.IsVirtual = IsVirtual;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getFileTaskDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFileId() {
        return FileId;
    }

    public void setFileId(Long FileId) {
        this.FileId = FileId;
    }

    public Long getTaskId() {
        return TaskId;
    }

    public void setTaskId(Long TaskId) {
        this.TaskId = TaskId;
    }

    public Boolean getIsVirtual() {
        return IsVirtual;
    }

    public void setIsVirtual(Boolean IsVirtual) {
        this.IsVirtual = IsVirtual;
    }

    /** To-one relationship, resolved on first access. */
    public File getFile() {
        Long __key = this.FileId;
        if (file__resolvedKey == null || !file__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            FileDao targetDao = daoSession.getFileDao();
            File fileNew = targetDao.load(__key);
            synchronized (this) {
                file = fileNew;
            	file__resolvedKey = __key;
            }
        }
        return file;
    }

    public void setFile(File file) {
        synchronized (this) {
            this.file = file;
            FileId = file == null ? null : file.getId();
            file__resolvedKey = FileId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Task getTask() {
        Long __key = this.TaskId;
        if (task__resolvedKey == null || !task__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TaskDao targetDao = daoSession.getTaskDao();
            Task taskNew = targetDao.load(__key);
            synchronized (this) {
                task = taskNew;
            	task__resolvedKey = __key;
            }
        }
        return task;
    }

    public void setTask(Task task) {
        synchronized (this) {
            this.task = task;
            TaskId = task == null ? null : task.getId();
            task__resolvedKey = TaskId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
