package biz.advancedcalendar.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import biz.advancedcalendar.greendao.FileTask;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FILE_TASK.
*/
public class FileTaskDao extends AbstractDao<FileTask, Long> {

    public static final String TABLENAME = "FILE_TASK";

    /**
     * Properties of entity FileTask.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FileId = new Property(1, Long.class, "FileId", false, "FILE_ID");
        public final static Property TaskId = new Property(2, Long.class, "TaskId", false, "TASK_ID");
        public final static Property IsVirtual = new Property(3, Boolean.class, "IsVirtual", false, "IS_VIRTUAL");
    };

    private DaoSession daoSession;

    private Query<FileTask> file_FileTaskListQuery;
    private Query<FileTask> task_FileTaskListQuery;

    public FileTaskDao(DaoConfig config) {
        super(config);
    }
    
    public FileTaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FILE_TASK' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FILE_ID' INTEGER," + // 1: FileId
                "'TASK_ID' INTEGER," + // 2: TaskId
                "'IS_VIRTUAL' INTEGER);"); // 3: IsVirtual
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_FILE_TASK_FILE_ID_TASK_ID ON FILE_TASK" +
                " (FILE_ID,TASK_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FILE_TASK'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FileTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long FileId = entity.getFileId();
        if (FileId != null) {
            stmt.bindLong(2, FileId);
        }
 
        Long TaskId = entity.getTaskId();
        if (TaskId != null) {
            stmt.bindLong(3, TaskId);
        }
 
        Boolean IsVirtual = entity.getIsVirtual();
        if (IsVirtual != null) {
            stmt.bindLong(4, IsVirtual ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(FileTask entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FileTask readEntity(Cursor cursor, int offset) {
        FileTask entity = new FileTask( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // FileId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // TaskId
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // IsVirtual
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FileTask entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFileId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTaskId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIsVirtual(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FileTask entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FileTask entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "fileTaskList" to-many relationship of File. */
    public List<FileTask> _queryFile_FileTaskList(Long FileId) {
        synchronized (this) {
            if (file_FileTaskListQuery == null) {
                QueryBuilder<FileTask> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FileId.eq(null));
                file_FileTaskListQuery = queryBuilder.build();
            }
        }
        Query<FileTask> query = file_FileTaskListQuery.forCurrentThread();
        query.setParameter(0, FileId);
        return query.list();
    }

    /** Internal query to resolve the "fileTaskList" to-many relationship of Task. */
    public List<FileTask> _queryTask_FileTaskList(Long TaskId) {
        synchronized (this) {
            if (task_FileTaskListQuery == null) {
                QueryBuilder<FileTask> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TaskId.eq(null));
                task_FileTaskListQuery = queryBuilder.build();
            }
        }
        Query<FileTask> query = task_FileTaskListQuery.forCurrentThread();
        query.setParameter(0, TaskId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFileDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTaskDao().getAllColumns());
            builder.append(" FROM FILE_TASK T");
            builder.append(" LEFT JOIN FILE T0 ON T.'FILE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN TASK T1 ON T.'TASK_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FileTask loadCurrentDeep(Cursor cursor, boolean lock) {
        FileTask entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        File file = loadCurrentOther(daoSession.getFileDao(), cursor, offset);
        entity.setFile(file);
        offset += daoSession.getFileDao().getAllColumns().length;

        Task task = loadCurrentOther(daoSession.getTaskDao(), cursor, offset);
        entity.setTask(task);

        return entity;    
    }

    public FileTask loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FileTask> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FileTask> list = new ArrayList<FileTask>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FileTask> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FileTask> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
