package biz.advancedcalendar.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCAL_CONFIRMED_LOGIN.
 */
public class LocalConfirmedLogin {

    private Long id;
    /** Not-null value. */
    private String UserName;
    private String AuthToken;

    public LocalConfirmedLogin() {
    }

    public LocalConfirmedLogin(Long id) {
        this.id = id;
    }

    public LocalConfirmedLogin(Long id, String UserName, String AuthToken) {
        this.id = id;
        this.UserName = UserName;
        this.AuthToken = AuthToken;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserName() {
        return UserName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getAuthToken() {
        return AuthToken;
    }

    public void setAuthToken(String AuthToken) {
        this.AuthToken = AuthToken;
    }

}
